### ISSUE TITLE
트잉여 닉네임에 :verified: 을 넣어서 트위터 인증마크 처럼 사용할 수 있는 문제

### ISSUE THREAD

**Issue by lunamoth** [twingyeo-kr/notice#12]
트잉여 닉네임 옆에 : verified : 이걸 넣으면 트위터 인증 마크가 달리는 것 같은데 이거 트위터에서 오신 분들이 보면 오해의 여지가 있을것 같군요.

이 이모지를 없애거나 닉네임 옆에 달수 없도록 하면 좋을것 같습니다.

운영자로 착각하거나, 위화감을 조성할 수 있을 것 같습니다.

**Comment by revi** [comment]
트위터의 문화를 마스토돈에서 무작정 받아주는 것에는 동의하기 어렵습니다.

**Comment by lunamoth** [comment]
> 트위터의 문화를 마스토돈에서 무작정 받아주는 것에는 동의하기 어렵습니다.

예 문화 차이는 인정합니다만,  트위터에서 이주하시는 분들도 존재하고 그 분들에게 오해의 여지가 있다는 점은 문제가 맞긴한 것 같습니다.

**Comment by Canorus** [comment]
반대합니다. 조금이라도 마스토돈을 써보면 이용자들이 오해한다거나 위화감을 느끼지 않는 것을 알 수 있습니다. 또 커스텀 이모지를 닉네임 옆에 붙이는 것은 마스토돈 자체의 기능이어서 이걸 굳이 변경할 필요가 적고, 커스텀 이모지는 개별 인스턴스에서 설정하는 것인데 모든 인스턴스마다 :verified: 이모지 삭제 요청을 하실건가요?

**Comment by unstabler** [comment]
:verified: emoji를 제거하는데 동의합니다.

다만, 다른 사용자분들로부터 투표 등을 받아서 결과대로 처리하는게 어떤가 싶습니다.

**Comment by revi** [comment]
그 부분에 대하여는 트위터에서 이주하시는 분들이 스스로 적응해야 할 문제라는 생각이 듭니다.
모든 것을 뉴비에게만 맞춰주는 것도 곤란하다는 생각이 많이 드는 요즘이네요.

**Comment by sftblw** [comment]
트잉여만 삭제한다고 될 일이 아니라 동의하지 않습니다. 금방 아시게 되는 거기도 하구요.

**Comment by BasixKOR** [comment]
한편으로 트위터 본판에서도 곧 verified 뱃지가 판매로 누구나 사용 가능하게 될 예정으로 보여서... 기존에 알고 있던 의미가 본판에서조차 퇴색된다면 트잉여에서 해당 의미론을 긍정해야 할지 다소 의문스럽습니다

**Comment by tribela** [comment]
예~전에 큐돈에서 모든 verified 에모지를 비활성으로 돌려본 적이 있습니다.
하지만 끝도 없는 일이기도 하고, 애초에 마스토돈에서 트위터의 verified 에모지를 붙이면 당연히 밈으로밖에 해석되지 않는 것이 정상입니다. 트위터에서 바로 밀려온 신규 사용자에게나 잠깐 혼란스러웠다가 "아 참 아니지"가 되지요
신규 사용자에게나 재밌는 밈이라서 결국은 아무도 안 쓰기도 합니다.

**Comment by lunamoth** [comment]
적어주신 답글들 보면 제가 과민하게 생각한것 같기도 하군요. 이슈 종료하는게 좋을것 같네요. (제가 닫아도 되는건지 모르겠습니다만.)
