### ISSUE TITLE
webP / webM 지원을 도입해주셨으면 합니다.

### ISSUE THREAD

**Issue by yeonggille** [twingyeo-kr/notice#13]
안녕하세요, 친애하는 운영진 여러분.
다름이 아니라, 신규 유저분들의 유입과 함께 webP나 webM을 사용해보시려는 분들이 계셨으나
트잉여 인스턴스에서 지원이 되지 않았기에 실망하시는 분들을 보게 되어
긴급한 사안은 아니고, 혹시라도 여유가 되실때에 마스토돈 최신버젼(에서는 VP9와 WebM, WebP 등을 지원하는 것으로 알고 있습니다.)
으로 판올림 해주시거나 혹은 외부 플러그인을 사용하여 지원을 확대해 주실 수 있으신가 여쭈어보고 싶습니다.
언제나 노고에 고생이 많으십니다.
감사합니다.

**Comment by unstabler** [comment]
다음 버전부터 도입됩니다!

**Comment by yeonggille** [comment]
감사합니다. 혹시나 해서 말인데 apng나 avif는 아직 도입이 안되었으려나요? 아직 점유율은 얼마 되지 않지만, 서버의 트래픽 및 리소스 부담을 조금이라도 덜어드리고 싶어서 여쭈어봅니다.

**Comment by saschanaz** [comment]
APNG는 없지만 AVIF는 4.0에서 도입됩니다. https://github.com/mastodon/mastodon/pull/19647

**Comment by yeonggille** [comment]
알려주셔서 감사합니다.

**Comment by yeonggille** [comment]
오늘부로 WebP가 올라가지는것을 확인했습니다. AV1 이미지 포맷은 올리면 들어는 가지는데, CW가 자동으로 씌워지는 버그가 있는데 이것은 마스토돈 리포쪽으로 이슈를 넣어야 하나요?

**Comment by saschanaz** [comment]
제 경우엔 AVIF는 아예 올라가질 않네요, https://github.com/mastodon/mastodon/issues/20834 등록했습니다.

(트잉여에선 되네요, 저는 CW가 씌워지는 버그는 없습니다)

**Comment by yeonggille** [comment]
등록해주셔서 감사합니다.
