### ISSUE TITLE
Markdown syntax highlight

### ISSUE THREAD

**Issue by Canorus** [twingyeo-kr/notice#4]
Twingyeo는 텍스트 포맷팅을 지원하지 않고 있습니다. 마스토돈 깃헙 리퐆에서도 이미 1년 이상 관련 이슈가 진행되고 있으나 별다른 업데이트가 없는 것으로 알고 있습니다. [issue - Text Formatting](https://github.com/tootsuite/mastodon/issues/853)

하지만 위의 이슈 중에 [스레드](https://github.com/tootsuite/mastodon/issues/853#issuecomment-382390889)에서는 [showdownjs](https://github.com/showdownjs/showdownv)를 통해서 인스턴스 단위로 마크다운 적용이 가능하고 이미 적용된 인스턴스가 있다고 적고 있습니다.

이런 플러그인이 아니더라도 기본적인 마크다운 문법(\*italic\*, \*\*bold\*\*, \*\*\*italic bold\*\*\*)은 적용할 수 있다고 생각합니다. 따라서 기본적인 마크다운 문법 중에 텍스트 하이라이트 관련 부분만이라도 적용하는 것을 건의하는 바입니다.

**Comment by BasixKOR** [comment]
좋은 의견이지만, 한편으로서는 해당 기능이 타 인스턴스와의 호환성 문제나 업데이트의 느려짐 등을 유발할 수도 있다고 생각합니다. 충분한 검증이 선행되어야 할 것 같아요.

**Comment by unstabler** [comment]
저는 좋은 것 같지만 타 클라이언트 호환성이 조금 걱정이네요 @ @);

**Comment by Canorus** [comment]
지금 다시 발견했는데 이건 인스턴스 레벨에 제기할 이슈가 아닌 것 같아서 일단 close 하겠습니다.
