### ISSUE TITLE
규칙 비호환 인스턴스(baraag.net; R-18)의 도메인 침묵 처리에 대해서

### ISSUE THREAD

**Issue by unstabler** [twingyeo-kr/notice#5]
# 개요
baraag.net 은 uncensored를 지향하여 NSFW로 마킹되지 않은 이미지를 공개적으로 포스트 하고 있기 때문에, 저희 인스턴스 규칙과 호환되지 않는다 판단되었습니다.

# 조치

- 도메인 차단 (침묵)
  - 도메인 차단 (침묵)은 해당 인스턴스의 공개 툿이 연합 타임라인에 나타나지 않도록 하는 기능입니다. 그러나 각 사용자는 해당 인스턴스의 사용자를 팔로우할 수 있고, 소통도 기존처럼 가능합니다.
  - **도메인 차단 (침묵)은 말 그대로의 도메인 차단을 의미하지 않습니다. 침묵 외에도 미디어 파일 거부와 서스펜드의 유형이 있으며 다른 유형의 차단에 대해서는 https://github.com/twingyeo-kr/notice/blob/master/domain-block.md 를 참고해 주세요.**

- ~미디어 파일 거부~
  - 미디어 파일 거부는 팔로우 하고 있어도 프로필 이미지와 첨부 미디어가 보기 힘들어지는 문제가 있어 침묵 조치를 하기로 했습니다.

# 후속 조치

- 해당 도메인으로부터 전송되는 미디어를 전부 NSFW로 마킹할 수 있는 기능이 생기면 침묵 해제 조치 후 NSFW 마킹 기능 사용

**Comment by unstabler** [comment]
다른 유형의 도메인 차단이나, 다른 도메인 차단 사례를 확인하시려면 https://github.com/twingyeo-kr/notice/blob/master/domain-block.md 를 참고해 주세요.

**Comment by unstabler** [comment]
찬성이나 다른 의견 있으면 코멘트 달아 주세요. 감사합니다.

**Comment by 4Y4N4** [comment]
찬성합니다

**Comment by sftblw** [comment]
[`@sftblw@twingyeo.kr`](https://twingyeo.kr/@sftblw) 입니다. 찬성합니다.

**Comment by BasixKOR** [comment]
@sftblw 님이 말씀하셨던 것처럼, "모든 미디어 NSFW" 가 나오면 그걸로 이전하는 쪽으로 계획해둔다면 어떨까요?

>일단 미디어 차단한 뒤 해당 이슈가 해결되면 모든 미디어에 NSFW 설정 이 딱 좋을 것 같아요 - sftblw

**Comment by unstabler** [comment]
@BasixKOR @sftblw 그게 좋을 것 같습니다.

**Comment by sftblw** [comment]
(논점외) 이슈 제목에 baraag.net 이 들어가면 좀 더 명확해질 것 같습니다.

**Comment by unstabler** [comment]
baraag.net 을 침묵 처리 하였습니다.
