### ISSUE TITLE
이용약관에 커스텀 에모지 신청 등의 바로가기를 추가해주세요

### ISSUE THREAD

**Issue by sftblw** [twingyeo-kr/notice#6]
- [커스텀 에모지 신청](https://docs.google.com/forms/d/e/1FAIpQLSdWsIEAfSHCArvLF27x1glDUBa7YbRw86cdzXxo4bJaNwkTnA/viewform)
- [이 저장소](https://github.com/twingyeo-kr/notice)

의 주소가 이용약관 란에 기술되어 유저가 찾아올 수 있었으면 좋겠습니다.

**Comment by unstabler** [comment]
처리가 늦어져서 죄송합니다. https://twingyeo.kr/about/more 의 상단에 추가하였습니다.

**Comment by unstabler** [comment]
혹시 보완했으면 하는 내용이 있으시면, 이 이슈를 다시 열어주세요. 감사합니다!
