### ISSUE TITLE
twingyeo.kr 규정을 위반하는 계정에 대한 신고

### ISSUE THREAD

**Issue by Canorus** [twingyeo-kr/notice#9]
![image](https://user-images.githubusercontent.com/7209435/54082548-c69ff480-435a-11e9-94bc-51421e8742bc.png)

@federationbot@mastodon.host 봇이 능동적으로 팔로우를 하여 규정을 위반하고 있는 바, 인스턴스 전역 차단이 필요할 것으로 사료됩니다.

**Comment by sftblw** [comment]
2019.05.05 자로 처리되었습니다.
